stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t jasonmarechal25/ubuntu-build-env/clang:latest .

push:
  stage: push
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push jasonmarechal25/ubuntu-build-env/clang:latest
  only:
    - main